version: '3.4'

services:

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - backend-network
        restart: always
    
    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        networks:
            - frontend-network
            - backend-network
        depends_on: 
            - mysql
        restart: always

    apache:
        build: ./apache
        depends_on: 
            - mysql
        restart: always
   
    lb:
        image: dockercloud/haproxy
        networks:
            - frontend-network
            - backend-network
        ports:
            - 80:80
            - 1936:1936
        links:
            - apache
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - backend-network
            - frontend-network
networks:
    frontend-network:
    backend-network:

volumes:
    mysql_data:
